In [1]:
import pandas as pd
import numpy as np
print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

In [2]:
dataset=pd.read_csv("kidney_disease.csv")

In [3]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [4]:
dataset.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [5]:
dataset.isna().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [6]:
dataset.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [26]:
def quanQual(dataset):
    quan=[]
    qual=[]
    for columnName in dataset.columns:
        #print(columnName)
        if(dataset[columnName].dtype=='O'):
            #print("qual")
            qual.append(columnName)
        else:
            #print("quan")
            quan.append(columnName)
    return quan,qual

In [27]:
quan,qual=quanQual(dataset)

In [52]:
dataset[quan]

      id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2    0.0  0.0  15.4
1      1   7.0  50.0  1.020  4.0  0.0    0.0  18.0  0.8    0.0  0.0  11.3
2      2  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8    0.0  0.0   9.6
3      3  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4    0.0  0.0  11.6
..   ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [53]:
dataset[qual]

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,normal,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,normal,normal,notpresent,notpresent,38,6000,0,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,0,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,good,no,no,notckd

In [54]:
quan_info=['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']
qual_info=['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad','appet', 'pe', 'ane']

for col in quan_info:
    dataset[col].fillna(0,inplace = True)

for col in qual_info:
    dataset[col].fillna(dataset[col].mode(),inplace=True)

C:\Users\anant\AppData\Local\Temp\ipykernel_5996\244110211.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset[col].fillna(0,inplace = True)
C:\Users\anant\AppData\Local\Temp\ipykernel_5996\244110211.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset[col].fillna(dataset[col].mode(),inplace=True)

In [55]:
dataset.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [56]:
dataset[quan]

      id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2    0.0  0.0  15.4
1      1   7.0  50.0  1.020  4.0  0.0    0.0  18.0  0.8    0.0  0.0  11.3
2      2  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8    0.0  0.0   9.6
3      3  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4    0.0  0.0  11.6
..   ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [57]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(dataset[quan])
df=imp.transform(dataset[quan])

In [58]:
df = pd.DataFrame(df,columns = quan)
df

        id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0.0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2    0.0  0.0  15.4
1      1.0   7.0  50.0  1.020  4.0  0.0    0.0  18.0  0.8    0.0  0.0  11.3
2      2.0  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8    0.0  0.0   9.6
3      3.0  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4.0  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4    0.0  0.0  11.6
..     ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395.0  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396.0  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397.0  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398.0  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399.0  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [59]:
imp

SimpleImputer()

In [60]:
df

        id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0.0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2    0.0  0.0  15.4
1      1.0   7.0  50.0  1.020  4.0  0.0    0.0  18.0  0.8    0.0  0.0  11.3
2      2.0  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8    0.0  0.0   9.6
3      3.0  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4.0  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4    0.0  0.0  11.6
..     ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395.0  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396.0  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397.0  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398.0  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399.0  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [61]:
cate=dataset[qaul]

In [62]:
df

        id   age    bp     sg   al   su    bgr    bu   sc    sod  pot  hemo
0      0.0  48.0  80.0  1.020  1.0  0.0  121.0  36.0  1.2    0.0  0.0  15.4
1      1.0   7.0  50.0  1.020  4.0  0.0    0.0  18.0  0.8    0.0  0.0  11.3
2      2.0  62.0  80.0  1.010  2.0  3.0  423.0  53.0  1.8    0.0  0.0   9.6
3      3.0  48.0  70.0  1.005  4.0  0.0  117.0  56.0  3.8  111.0  2.5  11.2
4      4.0  51.0  80.0  1.010  2.0  0.0  106.0  26.0  1.4    0.0  0.0  11.6
..     ...   ...   ...    ...  ...  ...    ...   ...  ...    ...  ...   ...
395  395.0  55.0  80.0  1.020  0.0  0.0  140.0  49.0  0.5  150.0  4.9  15.7
396  396.0  42.0  70.0  1.025  0.0  0.0   75.0  31.0  1.2  141.0  3.5  16.5
397  397.0  12.0  80.0  1.020  0.0  0.0  100.0  26.0  0.6  137.0  4.4  15.8
398  398.0  17.0  60.0  1.025  0.0  0.0  114.0  50.0  1.0  135.0  4.9  14.2
399  399.0  58.0  80.0  1.025  0.0  0.0  131.0  18.0  1.1  141.0  3.5  15.8

[400 rows x 12 columns]

In [63]:
cate

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,normal,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,normal,normal,notpresent,notpresent,38,6000,0,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,0,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,good,no,no,notckd

In [64]:
cate.columns

Index(['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [65]:
cate_cols=['rbc', 'pc', 'pcc', 'ba', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification']

for col in cate_cols:
    dataset[col]=dataset[col].replace(0,dataset[col].mode()[0])

In [66]:
cate

,rbc,pc,pcc,ba,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,normal,normal,notpresent,notpresent,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,normal,normal,notpresent,notpresent,38,6000,0,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,31,7500,0,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,47,6700,4.9,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,54,7800,6.2,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,49,6600,5.4,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,51,7200,5.9,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,53,6800,6.1,no,no,no,good,no,no,notckd

In [67]:
two=[df,cate]

In [68]:
preprocessed=pd.concat(two,axis=1)

In [69]:
preprocessed

,id,age,bp,sg,al,su,bgr,bu,sc,sod,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0.0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,0.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1.0,7.0,50.0,1.020,4.0,0.0,0.0,18.0,0.8,0.0,...,38,6000,0,no,no,no,good,no,no,ckd
2,2.0,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,0.0,...,31,7500,0,no,yes,no,poor,no,yes,ckd
3,3.0,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4.0,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,0.0,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395.0,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396.0,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397.0,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398.0,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399.0,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [70]:
preprocessed.isnull().sum()

id                0
age               0
bp                0
sg                0
al                0
su                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
rbc               0
pc                0
pcc               0
ba                0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [72]:
preprocessed.to_csv("PreCKD.csv",index=False)